---
- name: Install ab_callcenter_oss Service
  hosts: localhost
  become: yes
  vars:
    SERVICE_NAME: "{{ service_name }}"
    NGROK_URL: "{{ ngrok_url }}"
    BASE_DIR: "/home/abus/.antbuddy"
  tasks:
    - name: Đảm bảo thư mục {{ BASE_DIR }} tồn tại
      ansible.builtin.file:
        path: "{{ BASE_DIR }}"
        state: directory
        mode: '0755'

    - name: Xóa thư mục ab_callcenter_oss nếu tồn tại
      ansible.builtin.file:
        path: "{{ BASE_DIR }}/ab_callcenter_oss"
        state: absent

    - name: Tải file ab_callcenter_oss.tar.gz từ {{ NGROK_URL }}
      ansible.builtin.get_url:
        url: "{{ NGROK_URL }}/ab_callcenter_oss.tar.gz"
        dest: "{{ BASE_DIR }}/ab_callcenter_oss.tar.gz"
        mode: '0644'

    - name: Giải nén file ab_callcenter_oss.tar.gz
      ansible.builtin.unarchive:
        src: "{{ BASE_DIR }}/ab_callcenter_oss.tar.gz"
        dest: "{{ BASE_DIR }}/"
        remote_src: yes

    - name: Xóa file ab_callcenter_oss.tar.gz sau khi giải nén
      ansible.builtin.file:
        path: "{{ BASE_DIR }}/ab_callcenter_oss.tar.gz"
        state: absent

    - name: Cấp quyền đầy đủ cho thư mục ab_callcenter_oss
      ansible.builtin.file:
        path: "{{ BASE_DIR }}/ab_callcenter_oss"
        state: directory
        mode: '0777'
        recurse: yes

    - name: Khởi động dịch vụ bằng PM2 với đúng phiên bản Node.js
      shell: |
        export PATH="$HOME/.nvm/versions/node/v12.22.12/bin:$PATH" && \
        /root/.nvm/versions/node/v12.22.12/bin/pm2 reload 11
      args:
        executable: /bin/bash
