---
- name: Execute deployment steps on server
  hosts: ab-antring-01
  remote_user: root
  become: yes
  vars:
    node_env: "production"
    gulp_task: "templatecach"
    pm2_process_id: "10"

  tasks:
    - name: Execute all commands as antbuddy user
      become_user: antbuddy
      shell: |
        cd ~/.antbuddy/ab-prod-beta/ &&
        eval "$(ssh-agent -s)" &&
        ssh-add ~/.ssh/id_ed25519 &&
        git pull origin antbuddy-production &&
        NODE_ENV="{{ node_env }}" gulp "{{ gulp_task }}" &&
        ./update-asset-version.sh &&
        pm2 reload "{{ pm2_process_id }}"
      args:
        executable: /bin/bash

    - name: Print completion message
      debug:
        msg: "Deployment steps completed successfully!"
