- name: Sync local to server
  hosts: local-host
  tasks:
    - name: Copy tet_sync.txt to server using scp
      command: scp /home/antbuddy/ansible/saas/tet_sync.txt antbuddy@beeiq-cmc:/home/antbuddy/.prod/tet_sync.txt
