- name: Sync local to server
  hosts: localhost
  connection: local
  tasks:
    - name: Copy tet_sync.txt to server
      ansible.builtin.copy:
        src: /home/antbuddy/ansible/saas/tet_sync.txt
        dest: /home/antbuddy/.prod/tet_sync.txt
        remote_src: no