- name: Sync local to server
  hosts: localhost
  connection: local
  tasks:
    - name: Copy tet_sync.txt to server using scp
      command: scp -o StrictHostKeyChecking=no /home/antbuddy/ansible/saas/tet_sync.txt antbuddy@203.205.6.152:/home/antbuddy/.prod/tet_sync.txt
